### PR TITLE
Cat facts app

### PR DESCRIPTION
**Pull request by ENESAYDOGDUOGLU**
I updated my imPlementation and I add unit test. Can you check my work?

### CODE REVIEW

**Comment by safaaltunel** [comment]
You should change your base directory name as practice_app. I'm continuing reviewing your code

**Comment by safaaltunel** [comment]
I assume you used print statements for debugging purposes. You can delete them now, also you commented out old codes.

**Review by OnurSefa — APPROVED** [review]
Some minor changes may be needed on merge operation. Other than that, thanks for your feature implementation.

**Comment by ekingungor** [comment]
@ENESAYDOGDUOGLU  There are conflicts with the master branch. I would resolve them but I see something that **may** be problematic, about the key. So better you handle that. Other than that I have testes your API, and no issues on that.

**Comment by ENESAYDOGDUOGLU** [comment]
Due to conflicts, I've merged my code into master branch manually.

**Pull request closed without merging**
