### PR TITLE
Weather Api is created, requirements are specified

### PR DESCRIPTION
**Pull request by gulsahc**
Weather api simply gets forecast information of a location that user specifies. If a user does not want to get a specific location's forecast, user selects the option "OK" and gets the information of the last searched location. Please review the code and give feedback.

### CODE REVIEW

**Review by safaaltunel — CHANGES_REQUESTED** [review]
There are a lot of files that you should not push. You can use .gitignore file in this [link](https://github.com/bounswe/2021SpringGroup10/tree/SportEvent_App). Also virtual environment folder has a .gitignore file that prevents you from pushing that folder. If you do not have it, you can create one and put a single '*' in it(just a star, not ''). in the /venv folder.

**Comment by gulsahc** [comment]
Unnecessary files are deleted @safaaltunel

**Comment by fleafclover** [comment]
Everything seems great and there is no conflicts with base branch. Therefore we can merge it.

**Review by fleafclover — COMMENTED** [review]
Unit tests should check the results in addition to status.

**Review by ekremgezgen — APPROVED** [review]
Everything is clear. Well done. Thanks

**Comment by ekingungor** [comment]
All looks fine to me. Congrats.

**Comment by ekingungor** [comment]
Folder structure and rest looks fine. It's an okay for me. #

**Review by ekingungor — APPROVED** [review]
Folder structure and rest looks fine. It's an okay for me.

**Pull request merged**
