### PR TITLE
A simple sportsevents api created. All the required files and a .gitignore file is added.

### PR DESCRIPTION
**Pull request by safaaltunel**
This is a simple sport event creation API. Users must specify sport type and they can add description if they want. If they do not add a description, I am getting description using Decathlon Sports API. Please review my code and I really appreciate your feedbacks.

### CODE REVIEW

**Review by fleafclover — COMMENTED** [review]
Unit tests should be added. However you can implement them after merging operation. Except that one there is no problem.

**Review by tahakalkanli — APPROVED** [review]
looks good! thanks

**Comment by ENESAYDOGDUOGLU** [comment]
It would be better if you use Mongo as database because we decided to use it as a group.

**Comment by safaaltunel** [comment]
> Unit tests should be added. However you can implement them after merging operation. Except that one there is no problem.

Thank you mate. I've added unit tests.

**Comment by safaaltunel** [comment]
> It would be better if you use Mongo as database because we decided to use it as a group.

Yes, you are right. Using Mongo also simplifies my code. Thanks for the advice!

**Pull request merged**
